// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzL-y2G4Wed4cDvrsnzveWqw4GKsaE-5E',
    appId: '1:771035320377:web:b7f273b948f76c152ffde8',
    messagingSenderId: '771035320377',
    projectId: 'app1-a069a',
    authDomain: 'app1-a069a.firebaseapp.com',
    storageBucket: 'app1-a069a.appspot.com',
    measurementId: 'G-GHDB0JGP75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkDXjyHgrUuPfYCS2Kf8XL4wvtD9aGq0A',
    appId: '1:771035320377:android:91c80219aefaafbc2ffde8',
    messagingSenderId: '771035320377',
    projectId: 'app1-a069a',
    storageBucket: 'app1-a069a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9soMVKOIiaoY8OJkahqbQt514cSl-3sY',
    appId: '1:771035320377:ios:540219ad1ea58a192ffde8',
    messagingSenderId: '771035320377',
    projectId: 'app1-a069a',
    storageBucket: 'app1-a069a.appspot.com',
    iosClientId: '771035320377-pq6ehjfd11i6qc8og0nh4dnkk4fk9qqg.apps.googleusercontent.com',
    iosBundleId: 'com.jielin.myFirstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9soMVKOIiaoY8OJkahqbQt514cSl-3sY',
    appId: '1:771035320377:ios:540219ad1ea58a192ffde8',
    messagingSenderId: '771035320377',
    projectId: 'app1-a069a',
    storageBucket: 'app1-a069a.appspot.com',
    iosClientId: '771035320377-pq6ehjfd11i6qc8og0nh4dnkk4fk9qqg.apps.googleusercontent.com',
    iosBundleId: 'com.jielin.myFirstFlutterProject',
  );
}
